POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content":"vs code rest is an ok tool",
    "important":true
}
###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"amen",
    "important":true
}